services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_DATABASE: DragNDrop
    volumes:
      - mongo_data:/data/db

  backend:
    image: node:20-alpine
    volumes:
      - .:/app
    working_dir: /app/src/backend
    command: ["sh","-lc","npm ci --omit=dev && node app.js"]
    env_file: [.env]
    environment:
      PORT: "8080"
    depends_on: [mongo]
    ports: ["8080:8080"]

  frontend:
    build: ./src/frontend
    restart: unless-stopped
    depends_on: [backend]
    ports: ["8085:80"]

volumes:
  mongo_data:
